## *********************************************************
## 
## File autogenerated for the bluefox_cam package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'upper': 'DEFAULT', 'lower': 'groups', 'srcline': 235, 'name': 'Default', 'parent': 0, 'srcfile': '/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT', 'field': 'default', 'state': True, 'parentclass': '', 'groups': [], 'parameters': [{'srcline': 280, 'description': 'image type enum', 'max': 2, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'name': 'image_type', 'edit_method': "{'enum_description': 'An enum to set the image type', 'enum': [{'srcline': 8, 'description': 'distorted image', 'srcfile': '/home/josh/uni/project/bluefox_cam_node/catkin_ws/src/bluefox_cam_node/cfg/bluefox_cam_node.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'distorted'}, {'srcline': 9, 'description': 'undistorted image', 'srcfile': '/home/josh/uni/project/bluefox_cam_node/catkin_ws/src/bluefox_cam_node/cfg/bluefox_cam_node.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'undistorted'}, {'srcline': 10, 'description': 'rectified image', 'srcfile': '/home/josh/uni/project/bluefox_cam_node/catkin_ws/src/bluefox_cam_node/cfg/bluefox_cam_node.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'rectified'}]}", 'default': 0, 'level': 0, 'min': 0, 'type': 'int'}], 'type': '', 'id': 0}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])    
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

bluefox_cam_distorted = 0
bluefox_cam_undistorted = 1
bluefox_cam_rectified = 2
